### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by dergeberl** [stackitcloud/yawol#101]
Issue to track documentation topics from #96 

- [ ] `hack/packer-infrastructure/` - openstack specific settings (floating-net, dns-nameservers) #113 
- [ ] yawollet image build - openstack specific settings (flavor name, storage-class) #113 
- [ ] link to VPA docs  #114
- [ ] more details about the `openstack secret`  #114
- [ ] add example LoadBalance to try it out after installation, that work without `yawol.stackit.cloud/className: "test"` #114
